# config/services.yaml

parameters:
    # Put parameters here if needed

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Define your custom route loader service
    App\Routing\CustomRouteLoader:
        tags:
            - { name: routing.loader }
    Modules\:
        resource: '../Modules/'
        exclude: '../Modules/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Add more service definitions here if needed
